name: Build and Deploy
on:
  push:
    branches:
      - master
      - build-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # If you're using actions/checkout@v2 you must set persist-credentials to false in most
        # cases for the deployment to work correctly.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # probably need to make subsequent steps conditional on cache hit/miss
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        uses: actions/setup-node@v1

      - name: Build
        run: |
          npm install
          npm run build

      - name: Jekyll fix
        run: touch ${{ github.workspace }}/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
